<b>Features</b>
<br>
<p>
    <ul>
        <li>Copy & Paste any file or folder anywhere</li>
        <li>Integrated compression & millitary-grade encryption</li>
        <li>Teleport to... friends, other devices, cloud (not ready yet)</li>
        <li>Synchronization & backup (not ready yet)</li>
        <li>Multiple clipboards / copy & paste history (not ready yet)</li>
    </ul>
    More to come...
</p>
