<b>About</b>
<br><br>
G. Delaportas: <i>«The "impossible" is a word that does not exist in my vocabulary...»</i>
<p>
George A. Delaportas (38 years old) is a Greek Enterprise Architect, an IT Security Expert / Hacker and a Serial Entrepreneur.
<br><br>
For the last 15 years, Mr. Delaportas has been working in hi-tech companies around the globe. He participated in various projects in the Space Industry alongside ESA, NASA and JAXA.
He also co-developed the largest homeland & civilian security & real-time protection system (SafeCity). Due to his experience in military & paramilitary grade systems, he joined global defense 
projects and worked side by side with military, technology institutes, police departments and joined forces with well respected agencies. Mr. Delaportas is the Architect of 
GreyOS, the world's first Meta-OS. He is an AI pioneer and back in 2006 he developed an innovative ANN, G.A.N.N (Geeks A.N.N). In the past he contributed in the social media safety industry 
with his solution, Fake FB, a utility that discriminates fake profiles and recognizes pedophiles on Facebook. In 2012, Mr. Delaportas has been awarded by the "Who is Who" institute 
as one of the most influencing young scientists & entrepreneurs in Greece.
<br><br>
For more info please see the following links:
<br>
<a target="_blank" href="https://www.linkedin.com/in/gdelaportas">Linkedin</a>
<br>
<a target="_blank" href="https://kingston.academia.edu/GeorgeDelaportas">Academia</a>
</p>
