                <div id="header">
                	<?UTIL::Load_Section('languages');?>
                    <div class="logo">
                        <a href="/<?=LANG::Get('this');?>/" title="<?=UTIL::Load_Content('text_mouse_tag', 'static');?>">
                            <img src="/site/pix/logo.png">
                        </a>
                    </div>
                    <div class="motto"><?=UTIL::Load_Content('text_motto', 'static');?></div>
                </div>
