<u>Το πρόβλημα</u>
<br>
Have you ever thought how cumbersome your life has become the last five years when it comes to copying, storing and sharing files?<br>
Did you notice that we all have to keep several apps running, connected with different services on the cloud like Google Drive, One Drive, 
Dropbox, you name it...<br><br>
Let's face it. More than five years ago all you had to do is keep your files safe by putting them into another hard disk drive or a USB. 
Even then though, you had to do this tedious process over and over again and look for another HD drive or USB, so yes the Cloud saved your 
ass in many ways.<br><br>
Still, you struggle to upload/download or share those files among computers that you own or computer that you want access on. 
So you need to login, choose what and how you want to download or share, install the corresponding app on the receiving computer 
(if not already installed) or maybe use a web link so you have to login to your email and then...<br><br>
<i>"OK, STOP. MY BRAIN IS OFFICIALY <u>BURNED!</u>"</i><br><br>
I feel you dear user... I really do.<br>
So, how about integrating and simplifying these different approaches while giving you the option to choose whether to do one thing or 
the other or unify them into one? Even better, how can all these be done transparently without much intervention from you? :D
<br><br><br>
<u>Η λύση</u>
<br>
Meet <i>DELAPORTATION!</i><br>
The all-in-one solution that enables you to upload, donwload and share with a simple copy/paste. Yes it's that easy!<br><br>
DELAPORTATION empowers you to use the classic simple "copy/paste" approach and do all the above with a click or two. That's right,
no more strange configurations, special menus, difficult to use apps and dozens of logins. Just a simple copy and paste!<br><br>
So practically, DELAPORTATION extends the functionality of the copy and paste commands on your computer end gives you the flexibility 
to copy files from your computer and paste them into another one. We call this process "<i>Teleportation</i>".<br><br>
But... since branding is an important thing and the creator of this great solution has a unique style and attitude he decided to 
name it DELAPORTATION. The solution name comes from Delaportas (the surname of the author) and the Teleportation.<br><br>
It's a fact: '"<i>DELAPORTATION is teleportation of files with an attitude...</i>"
